### PR TITLE
Add pod specs for AmazonChimeSDKMachineLearning

### PR DESCRIPTION
**Pull request by richhx**
## ℹ️ Description
Add `AmazonChimeSDKMachineLearning*.podspec` files for bitcode and
non-bitcode versions. Dependencies are subsequently added to
`AmazonChimeSDK`. Although developers don't necessarily need the
library, this makes sure that if they want to use the features, the
transitive dependency is also imported.

This should only be merged after the AmazonChimeSDK v0.20.0 release
is finished.

### Issue #, if available
N/A

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
    - [ ] README update
    - [ ] CHANGELOG update
    - [ ] guildes update
- [x] This change requires a dependency update
    - [ ] Amazon Chime SDK Media
    - [x] Other (push AmazonChimeSDKMachineLearning to CocoaPods trunk)

## 🧪 How Has This Been Tested?
Verify that `AmazonChimeSDKDemoPods` works through localhost and a
private podspec repository.

### Additional Manual Test
- [x] Pause and resume remote video
- [x] Switch local camera
- [x] Rotate screen back and forth

## 📱 Screenshots, if available
N/A

#### Integration validation (required before release)

- [ ] Unit tests pass
- [ ] Build SDK against simulator with release options
- [ ] Build SDK against device with release options
- [ ] Build SDK against simulator with debug options
- [ ] Build SDK against device with debug options
- [ ] Test Demo against simulator with SDK (debug build) in workspace
- [ ] Test Demo against device with SDK (debug build) in workspace
- [ ] Test DemoObjC against simulator with SDK (debug build) in workspace
- [ ] Test DemoObjC against device with SDK (debug build) in workspace
- [ ] Test Demo against simulator with SDK.framework (release build)
- [ ] Test Demo against device with SDK.framework (release build)
- [ ] Test DemoObjC against simulator with SDK.framework (release build)
- [ ] Test DemoObjC against device with SDK.framework (release build)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by hokyungh — APPROVED** [review]

**Review by ziyiz-amzn — COMMENTED** [review]
The podspec file of AmazonChimeSDK will treat `AmazonChimeSDKMachineLearning-Bitcode` as a required dependency, it will download it when `pod install`. Shall we look into optional dependency in CocoaPods. - http://www.dbotha.com/2014/12/04/optional-cocoapod-dependencies/

**Comment by richhx** [comment]
Hmm that's an interesting idea. It looks like we'd need to change the AmazonChimeSDK build though to do this via the subspec-ing. I'm inclined to potentially do that in a future revision. Thoughts?

**Comment by richhx** [comment]
Seeing as I haven't tested the usage of the flags.

**Comment by ziyiz-amzn** [comment]
We can remove the ML dependency from SDK, treat ML pod separate with SDK pod. Demo app will declare two pods to import, like
```
target 'AmazonChimeSDKDemoPods' do
  use_frameworks!
  # Pods for AmazonChimeSDKDemoPods
  pod 'AmazonChimeSDK-Bitcode'
  pod 'AmazonChimeSDKMachineLearning-Bitcode'
end
```

**Review by ziyiz-amzn — APPROVED** [review]

**Review by hokyungh — APPROVED** [review]

**Pull request merged**
